import DrawerAppBar from "@/components/Navbar";
import MuiProviders from '@/app/provider';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MuiProviders>
          <DrawerAppBar />
          {children}
        </MuiProviders>
      </body>
    </html>
  );
};